version: '3.5'

services:
  db:
    build: ./.docker/mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD:-root}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME:-mood_hound}
      MONGO_HOST: localhost
      MONGO_PORT: "27017"
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGODB_USER:-root}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGODB_PASSWORD:-root}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD:-root}
    depends_on:
      - db

